/**
 * TransitMY bilingual copy — BM first (brand voice), EN second.
 * Keys are grouped by surface. Add both languages or the type errors.
 */

const ms = {
  // ── Brand / shared ─────────────────────────────────────────────────────────
  'app.name': 'TransitMY',
  'common.live': 'Live',
  'common.back': 'Kembali',
  'common.backHome': 'Kembali ke laman utama',
  'common.loading': 'Memuatkan…',
  'common.min': 'min',
  'common.walk': 'jalan kaki',
  'common.stops': 'hentian',
  'common.source': 'Sumber: data.gov.my',

  // ── Nav ────────────────────────────────────────────────────────────────────
  'nav.home': 'Utama',
  'nav.map': 'Peta',
  'nav.plan': 'Rancang',
  'nav.ktmb': 'KTM',
  'nav.report': 'Laporan',
  'nav.status': 'Status',

  // ── Home ───────────────────────────────────────────────────────────────────
  'home.greet.morning': 'Selamat pagi',
  'home.greet.midday': 'Selamat tengah hari',
  'home.greet.evening': 'Selamat petang',
  'home.greet.night': 'Selamat malam',
  'home.search.placeholder': 'Cari hentian atau laluan…',
  'home.search.aria': 'Cari hentian',
  'home.nearby': 'Berdekatan',
  'home.nearby.nearYou': 'Dekat anda',
  'home.nearby.filterNone': 'Tiada hentian jenis ini berdekatan — cuba tapis "Semua"',
  'home.nearby.noArrivals': 'Tiada ketibaan dalam 90 minit akan datang',
  'home.nearby.loadFailed': 'Tak dapat muatkan hentian berdekatan',
  'home.nearby.noneWithin': 'Tiada hentian dalam',
  'home.nearby.geoDenied': 'Akses lokasi ditolak — menunjukkan sekitar KL Sentral',
  'home.nearby.getCloser': 'Cuba dekati mana-mana hentian transit',
  'home.nearby.detect': 'Kesan lokasi saya',
  'home.nearby.locating': 'Mengesan lokasi…',
  'home.saved': 'Disimpan',
  'home.saved.empty': 'Simpan hentian yang kerap anda guna — ia muncul di sini dahulu.',
  'home.routine': 'Rutin anda',
  'home.routine.learned': 'dipelajari pada peranti anda',
  'home.routine.next': 'Seterusnya',
  'home.routine.checking': 'Menyemak jadual…',
  'home.routine.noService': 'Tiada perkhidmatan sekarang',
  'home.pulse.eyebrow': 'Denyut rangkaian',
  'home.pulse.tracked': 'kenderaan dijejak secara langsung',
  'home.pulse.honesty': 'Sumber: data.gov.my · LRT/MRT tiada suapan langsung',
  'home.pulse.stale': 'Data mungkin lewat',

  // ── Search overlay ─────────────────────────────────────────────────────────
  'search.placeholder': 'Cari hentian…',
  'search.close': 'Tutup carian',
  'search.clear': 'Kosongkan',
  'search.searching': 'Mencari',
  'search.idle.title': 'Cari nama hentian',
  'search.idle.desc': 'Meliputi RapidKL Bas, Rapid Rail (LRT / MRT / Monorel) dan perkhidmatan KTM',
  'search.idle.hint': 'Ketuk rangkaian untuk menapis',
  'search.noMatch': 'Tiada hentian sepadan',
  'search.allNetworks': 'Cari dalam semua rangkaian',
  'search.aria': 'Carian hentian',
  'search.filter.all': 'Semua',
  'search.filter.bus': 'Bas',
  'search.filter.rail': 'Rel',
  'search.filter.ktm': 'KTM',

  // ── Plan (Rancang) ─────────────────────────────────────────────────────────
  'plan.title.1': 'Rancang',
  'plan.title.2': 'perjalanan.',
  'plan.from': 'Dari',
  'plan.to': 'Ke',
  'plan.pickStop': 'Pilih hentian…',
  'plan.swap': 'Tukar arah',
  'plan.useLocation': 'Guna lokasi saya',
  'plan.locating': 'Mencari hentian terdekat…',
  'plan.intro': 'Sambung MRT ↔ LRT ↔ Monorel ↔ KTM dalam satu perjalanan — kami cari laluan terus dan pertukaran antara rangkaian.',
  'plan.loading': 'Mencari laluan terbaik…',
  'plan.failed': 'Tak dapat merancang sekarang — cuba sebentar lagi.',
  'plan.none': 'Tiada perkhidmatan ditemui dalam 2 jam akan datang — mungkin sudah lewat malam, atau laluan ini perlukan pertukaran yang belum kami sokong.',
  'plan.busCross': 'Perancangan silang rangkaian untuk bas belum kami sokong — kami tak nak beri anggaran yang kami tak yakin. Untuk bas, pilih dua hentian bas; untuk rel + KTM, semua kombinasi boleh.',
  'plan.transferAt': 'Tukar di',
  'plan.sameStation': 'stesen sama',
  'plan.walkTransfer': 'jalan kaki',
  'plan.walkStart': 'Jalan ke',
  'plan.walkEnd': 'Jalan ke destinasi',
  'plan.footnote': 'Waktu berjadual · jadual data.gov.my · masa tukar termasuk jalan kaki',
  'plan.service': 'Perkhidmatan',
  'plan.transfers.0': 'Terus',
  'plan.transfers.1': '1 pertukaran',
  'plan.transfers.n': 'pertukaran',
  'plan.details': 'Ketuk untuk perincian',
  'plan.detail.title': 'Perincian perjalanan',
  'plan.detail.board': 'Naik di',
  'plan.detail.alight': 'Turun di',
  'plan.detail.depart': 'Bertolak',
  'plan.detail.arrive': 'Tiba',

  // ── Places (malls / hospitals / attractions) ───────────────────────────────
  'places.title': 'Pergi ke tempat menarik',
  'places.desc': 'Semua boleh sampai dengan pengangkutan awam — ketuk untuk jadikan destinasi.',
  'places.mall': 'Pusat Beli-belah',
  'places.hospital': 'Hospital',
  'places.attraction': 'Tarikan',
  'places.walkFrom': 'dari',
  'places.loading': 'Memuatkan tempat…',
  'places.failed': 'Tak dapat muatkan senarai tempat sekarang.',

  // ── Map (Peta) ─────────────────────────────────────────────────────────────
  'map.title': 'Peta Langsung',
  'map.loading': 'Memuatkan peta…',
  'map.pickBusRoute': 'Pilih laluan bas untuk melihat kenderaan langsung',
  'map.loadingLive': 'Memuatkan kedudukan langsung…',
  'map.noTrains': 'Tiada tren KTM aktif sekarang',
  'map.noBuses': 'Tiada bas aktif untuk laluan ini sekarang',
  'map.train': 'tren',
  'map.bus': 'bas',
  'map.liveSuffix': 'langsung',
  'map.maybeLate': '· data mungkin lewat',
  'map.locate': 'Lokasi saya',
  'map.locating': 'Mengesan…',
  'map.nearbyBuses': 'bas berdekatan anda',
  'map.noNearbyBuses': 'Tiada bas dalam 3 km — pilih laluan untuk lihat semua bas',
  'map.locateHint': 'Kesan lokasi anda untuk lihat bas berdekatan, atau pilih laluan',
  'map.refresh': '· kemas kini tiap 15s',
  'map.ktmInfo': 'Semua tren KTM aktif ditunjukkan pada kedudukan GPS sebenar, dikemas kini setiap 15 saat. KTM tiada penapisan per-laluan.',
  'map.routes': 'laluan',
  'map.scrollMore': 'skrol untuk lagi',
  'map.loadingRoutes': 'Memuatkan laluan…',
  'map.noMatchingRoutes': 'Tiada laluan sepadan',
  'map.changeRoute': 'Tukar',
  'map.clearRoute': 'Kosongkan',

  // ── Stop sheet ─────────────────────────────────────────────────────────────
  'sheet.save': 'Simpan',
  'sheet.saved': 'Disimpan',
  'sheet.noArrivals': 'Tiada ketibaan dalam 90 minit akan datang',
  'sheet.share': 'Kongsi resit perjalanan',
  'sheet.saveAria': 'Simpan hentian ini',
  'sheet.removeAria': 'Buang daripada disimpan',
} as const

export type StringKey = keyof typeof ms

const en: Record<StringKey, string> = {
  'app.name': 'TransitMY',
  'common.live': 'Live',
  'common.back': 'Back',
  'common.backHome': 'Back to home',
  'common.loading': 'Loading…',
  'common.min': 'min',
  'common.walk': 'walk',
  'common.stops': 'stops',
  'common.source': 'Source: data.gov.my',

  'nav.home': 'Home',
  'nav.map': 'Map',
  'nav.plan': 'Plan',
  'nav.ktmb': 'KTM',
  'nav.report': 'Report',
  'nav.status': 'Status',

  'home.greet.morning': 'Good morning',
  'home.greet.midday': 'Good afternoon',
  'home.greet.evening': 'Good evening',
  'home.greet.night': 'Good night',
  'home.search.placeholder': 'Search stops or routes…',
  'home.search.aria': 'Search stops',
  'home.nearby': 'Nearby',
  'home.nearby.nearYou': 'Near you',
  'home.nearby.filterNone': 'No stops of this type nearby — try the "All" filter',
  'home.nearby.noArrivals': 'No arrivals in the next 90 minutes',
  'home.nearby.loadFailed': "Couldn't load nearby stops",
  'home.nearby.noneWithin': 'No stops within',
  'home.nearby.geoDenied': 'Location denied — showing around KL Sentral',
  'home.nearby.getCloser': 'Try getting closer to any transit stop',
  'home.nearby.detect': 'Detect my location',
  'home.nearby.locating': 'Locating…',
  'home.saved': 'Saved',
  'home.saved.empty': 'Save the stops you use often — they show up here first.',
  'home.routine': 'Your routine',
  'home.routine.learned': 'learned on your device',
  'home.routine.next': 'Next',
  'home.routine.checking': 'Checking schedule…',
  'home.routine.noService': 'No service right now',
  'home.pulse.eyebrow': 'Network pulse',
  'home.pulse.tracked': 'vehicles tracked live',
  'home.pulse.honesty': 'Source: data.gov.my · LRT/MRT has no live feed',
  'home.pulse.stale': 'Data may be delayed',

  'search.placeholder': 'Search stops…',
  'search.close': 'Close search',
  'search.clear': 'Clear',
  'search.searching': 'Searching',
  'search.idle.title': 'Search by stop name',
  'search.idle.desc': 'Covers RapidKL Bus, Rapid Rail (LRT / MRT / Monorail) and KTM services',
  'search.idle.hint': 'Tap a network to filter',
  'search.noMatch': 'No stops matching',
  'search.allNetworks': 'Search all networks',
  'search.aria': 'Stop search',
  'search.filter.all': 'All',
  'search.filter.bus': 'Bus',
  'search.filter.rail': 'Rail',
  'search.filter.ktm': 'KTM',

  'plan.title.1': 'Plan a',
  'plan.title.2': 'journey.',
  'plan.from': 'From',
  'plan.to': 'To',
  'plan.pickStop': 'Pick a stop…',
  'plan.swap': 'Swap direction',
  'plan.useLocation': 'Use my location',
  'plan.locating': 'Finding nearest stop…',
  'plan.intro': 'Connect MRT ↔ LRT ↔ Monorail ↔ KTM in one trip — we find direct rides and cross-network transfers.',
  'plan.loading': 'Finding the best route…',
  'plan.failed': "Can't plan right now — try again shortly.",
  'plan.none': 'No service found in the next 2 hours — it may be late at night, or this route needs a transfer we don\'t support yet.',
  'plan.busCross': "Cross-network planning for buses isn't supported yet — we won't give you an estimate we're not confident in. For buses, pick two bus stops; rail + KTM combinations all work.",
  'plan.transferAt': 'Transfer at',
  'plan.sameStation': 'same station',
  'plan.walkTransfer': 'walk',
  'plan.walkStart': 'Walk to',
  'plan.walkEnd': 'Walk to destination',
  'plan.footnote': 'Scheduled times · data.gov.my timetable · transfer time includes walking',
  'plan.service': 'Service',
  'plan.transfers.0': 'Direct',
  'plan.transfers.1': '1 transfer',
  'plan.transfers.n': 'transfers',
  'plan.details': 'Tap for details',
  'plan.detail.title': 'Journey details',
  'plan.detail.board': 'Board at',
  'plan.detail.alight': 'Alight at',
  'plan.detail.depart': 'Depart',
  'plan.detail.arrive': 'Arrive',

  'places.title': 'Go somewhere great',
  'places.desc': 'All reachable by public transport — tap one to set it as your destination.',
  'places.mall': 'Malls',
  'places.hospital': 'Hospitals',
  'places.attraction': 'Attractions',
  'places.walkFrom': 'from',
  'places.loading': 'Loading places…',
  'places.failed': "Couldn't load places right now.",

  'map.title': 'Live Map',
  'map.loading': 'Loading map…',
  'map.pickBusRoute': 'Pick a bus route to see live vehicles',
  'map.loadingLive': 'Loading live positions…',
  'map.noTrains': 'No KTM trains active right now',
  'map.noBuses': 'No buses active on this route right now',
  'map.train': 'train',
  'map.bus': 'bus',
  'map.liveSuffix': 'live',
  'map.maybeLate': '· data may be delayed',
  'map.locate': 'My location',
  'map.locating': 'Locating…',
  'map.nearbyBuses': 'buses near you',
  'map.noNearbyBuses': 'No buses within 3 km — pick a route to see all buses',
  'map.locateHint': 'Detect your location to see nearby buses, or pick a route',
  'map.refresh': '· updates every 15s',
  'map.ktmInfo': 'Every active KTM train is shown at its real GPS position, updated every 15 seconds. KTM has no per-route filter.',
  'map.routes': 'routes',
  'map.scrollMore': 'scroll for more',
  'map.loadingRoutes': 'Loading routes…',
  'map.noMatchingRoutes': 'No matching routes',
  'map.changeRoute': 'Change',
  'map.clearRoute': 'Clear',

  'sheet.save': 'Save',
  'sheet.saved': 'Saved',
  'sheet.noArrivals': 'No arrivals in the next 90 minutes',
  'sheet.share': 'Share journey receipt',
  'sheet.saveAria': 'Save this stop',
  'sheet.removeAria': 'Remove from saved',
}

export const STRINGS = { ms, en } as const

/** Localised day/month short names for date eyebrows. */
export const DAYS = {
  ms: ['Ahad', 'Isnin', 'Selasa', 'Rabu', 'Khamis', 'Jumaat', 'Sabtu'],
  en: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
} as const

export const MONTHS = {
  ms: ['Jan', 'Feb', 'Mac', 'Apr', 'Mei', 'Jun', 'Jul', 'Ogos', 'Sep', 'Okt', 'Nov', 'Dis'],
  en: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
} as const

/**
 * Feel-good one-liners shown under the greeting. The voice: a friend who SEES
 * the commuter — the early alarms, the packed train, the sweat of going to
 * work, the loved ones waiting at home — and makes it all feel worth it.
 * Kept short so they sit on one or two lines, warm Malaysian "kau" register,
 * never preachy. Pick one at random per visit (client-side — see HomeLayout).
 */
export const QUOTES: { ms: string; en: string }[] = [
  { ms: 'Titik peluh pagi ini bukan sia-sia — ada senyuman menunggu kau di rumah.', en: "This morning's sweat isn't for nothing — there's a smile waiting for you at home." },
  { ms: 'Kau bukan sekadar pergi kerja. Kau sedang bina masa depan orang tersayang.', en: "You're not just going to work — you're building a future for the people you love." },
  { ms: 'Penat hari ini, rezeki esok. Semangat!', en: "Today's tiredness is tomorrow's rezeki. Keep going!" },
  { ms: 'Setiap perjalanan pagi ini, ada yang doakan kau selamat sampai.', en: 'Someone prayed for you to arrive safely today.' },
  { ms: 'Peluh tu tanda kau berjuang. Bangga dengan diri sendiri.', en: "That sweat means you're fighting for something. Be proud of yourself." },
  { ms: 'Jauh mana pun perjalanan, rumah tetap tunggu kau pulang.', en: 'However far you travel, home will always wait for you.' },
  { ms: 'Kerja keras kau hari ini, cerita bangga keluarga esok.', en: "Your hard work today is your family's proud story tomorrow." },
  { ms: 'Sarapan boleh tertinggal, tapi semangat jangan.', en: 'You can skip breakfast, but never skip your spirit.' },
  { ms: 'Tren sesak pun, hati kau tetap luas. Terima kasih sebab tak putus asa.', en: 'The train may be packed, but your heart is bigger. Thank you for not giving up.' },
  { ms: 'Ada kesayangan tunggu di rumah — sebab paling cantik untuk pulang dengan selamat.', en: 'Someone you love is waiting at home — the most beautiful reason to travel safe.' },
  { ms: 'Bukan senang bangun awal setiap hari. Tapi kau buat jugak. Hebat.', en: "Waking up early every day isn't easy. But you do it anyway. That's strength." },
  { ms: 'Gaji masuk sebulan sekali, tapi usaha kau masuk setiap hari.', en: 'Payday comes once a month, but your effort shows up every single day.' },
  { ms: 'Perjalanan jauh hari ini, langkah dekat ke impian kau.', en: "Today's long commute is one step closer to your dreams." },
  { ms: 'Letih itu sementara. Bangga keluarga pada kau, kekal.', en: "Tiredness is temporary. Your family's pride in you is forever." },
  { ms: 'Tak perlu sempurna hari ini — cukup sekadar hadir dan cuba.', en: "You don't have to be perfect today — showing up is already enough." },
  { ms: 'Setiap stesen yang kau lalui, satu pengorbanan yang orang rumah hargai.', en: 'Every station you pass is a sacrifice someone at home appreciates.' },
  { ms: 'Malam ini, balik dan peluk orang yang kau sayang. Kau layak.', en: "Tonight, go home and hug the ones you love. You've earned it." },
  { ms: 'Rezeki tak pernah tersalah alamat. Teruskan usaha.', en: 'Rezeki never gets lost in the mail. Keep at it.' },
  { ms: 'Kau penat sebab kau berusaha. Itu bukan kelemahan — itu bukti.', en: "You're tired because you're trying. That's not weakness — that's proof." },
  { ms: 'Perjalanan pulang terasa lebih ringan bila tahu ada yang menanti.', en: 'The ride home always feels lighter when someone is waiting.' },
]
